version: '3.7'
services:

  mysql_db:
    container_name: template_db
    image: mysql:5.7.26
    command: mysqld --verbose --sql-mode="NO_ENGINE_SUBSTITUTION" --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: "template_db"
      MYSQL_USER: "appUser"
      MYSQL_PASSWORD: "pwd"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306

  db-migration:
    image: migration
    restart: on-failure
    environment:
      - spring.datasource.url
      - db.username=
    depends_on:
      - mysql_db

  webapp:
    image: template:latest
    restart: unless-stopped
    build:
      context: '.'
    depends_on:
      - db-migration
